### ISSUE TITLE
is azurereader3 supposed to replace azurereader2?

### ISSUE THREAD

**Issue by weihangChen** [Gibe/ImageResizer.Plugins.AzureReader3#1]
I was trying azurereader2, does not work, then try azurereader3, same problem. the problem is that it only make a redirect to the blog, when a query parameter is used, then it stops working

is there any sample application avaialbe on githug? 

regards
Marc

**Comment by stevetemple** [comment]
This is the same code as AzureReader2 except it's been compiled with v3 of the Azure libraries for compatibility with other components of our site. It's not an official ImageResizer plugin.

If it stops working when you use a querystring param like ?width=100 then it's when the resizer element kicks in that it's failing. Double check all of your config first and make sure your keys and urls are correct

**Comment by weihangChen** [comment]
I actually have the same problem described in this thread
http://stackoverflow.com/questions/26469728/imageresizer-azurereader2-plugin-404-response-to-resize-request

we are replacing the existing SQL plugin with the AzureBlob storage when we are moving our application to Azure. 
1.What I do not understand from the thread is that, how does the url rewriting work here (i am not good at imageresizing api). any code sample?
2.Any sample XML connecting to a blobcontainer in the documentation? 

I do have diskcache plugin as well, so whenever an image is read from the SQL, I see that under "imagecache" folder, the image is populated there, but when I switch to AzureReader2/3, that folder does not get populated at all, so it is not that query plugin that does not work, but the whole thing is not working

here is my configuration

```
 <add name="AzureReader3" connectionString="DefaultEndpointsProtocol=http;AccountName=[account];AccountKey=[key]" endpoint="http://****.blob.core.windows.net/"     
            prefix="~/azure/" redirectToBlobIfUnmodified="false" requireImageExtension="true" cacheUnmodifiedFiles="true" checkForModifiedFiles="true" vpp="true" untrustedData="false" />
```

when i access the image from my local server ( "images" is my blob container )
**http://localhost/WebApplication2/azure/images/chair.jpg**
it redirects to 
**http://*****.blob.core.windows.net/images/chair.jpg**

if it behaves correctly, it is supposed to stay within "localhost/WebApplication2"



Regards
Marc

**Comment by weihangChen** [comment]
Hi
sorry for wasting your time, the answer from stackoverflow is right, I am not supposed to have container appended in the endpoint, instead I put it in the prefix, then it starts working


```
<add name="AzureReader3" connectionString="DefaultEndpointsProtocol=http;AccountName=[account];AccountKey=[key]" endpoint="http://****.blob.core.windows.net/"     
            prefix="~/[containername]/"  />
```
